# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20160613_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='poids',
            name='ordre',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
