# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 02:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_poids_ordre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poids',
            options={'verbose_name_plural': 'poids'},
        ),
    ]
