# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-26 17:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_auto_20160626_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
